module US
  extend ActiveSupport::Concern
  
  module ClassMethods
    def states
      Array["AK", "ak", "alaska",
            "AL", "al", "alabama",
            "AR", "ar", "arkansas",
            "AS", "as", "american Samoa",
            "AZ", "az", "arizona",
            "CA", "ca", "california",
            "CO", "co", "colorado",
            "CT", "ct", "connecticut",
            "DC", "dc", "district of Columbia",
            "DE", "de", "delaware",
            "FL", "fl", "florida",
            "GA", "ga", "georgia",
            "GU", "gu", "guam",
            "HI", "hi", "hawaii",
            "IA", "ia", "iowa",
            "ID", "id", "idaho",
            "IL", "il", "illinois",
            "IN", "in", "indiana",
            "KS", "ks", "kansas",
            "KY", "ky", "kentucky",
            "LA", "la", "louisiana",
            "MA", "ma", "massachusetts",
            "MD", "md", "maryland",
            "ME", "me", "maine",
            "MI", "mi", "michigan",
            "MN", "mn", "minnesota",
            "MO", "mo", "missouri",
            "MS", "ms", "mississippi",
            "MT", "mt", "montana",
            "NC", "nc", "north Carolina",
            "ND", "nd", "north Dakota",
            "NE", "ne", "nebraska",
            "NH", "nh", "new Hampshire",
            "NJ", "nj", "new Jersey",
            "NM", "nm", "new Mexico",
            "NV", "nv", "nevada",
            "NY", "ny", "new York",
            "OH", "oh", "ohio",
            "OK", "ok", "oklahoma",
            "OR", "or", "oregon",
            "PA", "pa", "pennsylvania",
            "PR", "pr", "puerto Rico",
            "RI", "ri", "rhode Island",
            "SC", "sc", "south Carolina",
            "SD", "sd", "south Dakota",
            "TN", "tn", "tennessee",
            "TX", "tx", "texas",
            "UT", "ut", "utah",
            "VA", "va", "virginia",
            "VI", "vi", "virgin Islands",
            "VT", "vt", "vermont",
            "WA", "wa", "washington",
            "WI", "wi", "wisconsin",
            "WV", "wv", "west Virginia",
            "WY", "wy", "wyoming"
             ]
    end
  end
end
